### ISSUE TITLE
Python Scenario fails

### ISSUE THREAD

**Issue by zdbasset** [argoproj-labs/katacoda-scenarios#10]
I realize this is a "work in progress" but I was not able to even start. The install of `couler` fails:
```
controlplane $ pip3 install git+https://github.com/couler-proj/couler@v0.1.1rc8-stable
Collecting git+https://github.com/couler-proj/couler@v0.1.1rc8-stable
  Cloning https://github.com/couler-proj/couler (to revision v0.1.1rc8-stable) to /tmp/pip-req-build-yj7xv69q
Collecting Deprecated
  Downloading Deprecated-1.2.12-py2.py3-none-any.whl (9.5 kB)
...
Successfully built couler wrapt
Installing collected packages: wrapt, Deprecated, websocket-client, docker, pyyaml, oauthlib, requests-oauthlib, pyasn1, rsa, cachetools, pyasn1-modules, google-auth, python-dateutil, urllib3, kubernetes, pyaml, couler
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.12
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
WARNING: You are using pip version 20.2.4; however, version 21.2.4 is available.
You should consider upgrading via the '/usr/bin/python3.8 -m pip install --upgrade pip' command.

controlplane $ python3 coin_flip_example.py
Traceback (most recent call last):
  File "coin_flip_example.py", line 1, in <module>
    import couler.argo as couler
ModuleNotFoundError: No module named 'couler'
```

**Comment by terrytangyuan** [comment]
Thanks for reporting. I'll take a look.

**Comment by terrytangyuan** [comment]
Please add `--ignore-installed` when running `pip3 install`. I've submitted #11 to fix this in tutorial as well.

**Comment by zdbasset** [comment]
Thanks. That fixed it.
-David-

--
David R. Steiner
Virtualization Lead/System Administrator
Enterprise Systems Group
Information, Technology & Consulting
Dartmouth College
Hanover, NH
Phone: 603.646.3127


From: Yuan Tang ***@***.***>
Reply-To: argoproj-labs/katacoda-scenarios ***@***.***>
Date: Thursday, September 2, 2021 at 8:45 PM
To: argoproj-labs/katacoda-scenarios ***@***.***>
Cc: "David R. Steiner" ***@***.***>, Author ***@***.***>
Subject: Re: [argoproj-labs/katacoda-scenarios] Python Scenario fails (#10)


Please add --ignore-installed when running pip3 install. I've submitted #11<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fargoproj-labs%2Fkatacoda-scenarios%2Fpull%2F11&data=04%7C01%7Cdavid.r.steiner%40dartmouth.edu%7C40f4b5947dd647c8ed8108d96e742ab3%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C637662267484866720%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fvknpmmDDNiZkFpYun1qI0n75lHFd3bKrlXvgR9ZLn8%3D&reserved=0> to fix this in tutorial as well.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fargoproj-labs%2Fkatacoda-scenarios%2Fissues%2F10%23issuecomment-912164571&data=04%7C01%7Cdavid.r.steiner%40dartmouth.edu%7C40f4b5947dd647c8ed8108d96e742ab3%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C637662267484876674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OVluUvDTgFKcx8BE8tQYV0r5xKq03OMKH%2BI6pEOoxkA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACA2E5OO5ZNAOPSAWFK6E7LUAALDTANCNFSM5DG2SGSA&data=04%7C01%7Cdavid.r.steiner%40dartmouth.edu%7C40f4b5947dd647c8ed8108d96e742ab3%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C637662267484876674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=k6LvDxB4ZQ3ooj6g2pl%2B8rqyFZRzQrbNJp%2BPdVNrMYM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdavid.r.steiner%40dartmouth.edu%7C40f4b5947dd647c8ed8108d96e742ab3%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C637662267484886632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NzeHNOIHcReVKdYh2zw%2Fol6lBMCd6mqirCkYA5KSUi0%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdavid.r.steiner%40dartmouth.edu%7C40f4b5947dd647c8ed8108d96e742ab3%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C637662267484886632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=koIrLZ4gZ1l1xM5SrpI4PxPKuJVZuRolzeQroxfWjZE%3D&reserved=0>.
